modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-v3"

[[mods]]
modId="grassnotfloating"
version="${file.jarVersion}"
displayName="GrassNotFloating"
authors="TeamPotato"
description='''
The grass generation should not occur on air.
'''